server:
    port: 8081

spring:
    application:
        name: ods-demo

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/ods?autoReconnect=true&useSSL=false&useUnicode=true&amp;charaterEncoding=utf-8
        username: wumrwds

mybatis:
    config-location: classpath:mybatis.cfg.xml
    mapper-locations: classpath:mappers/*.xml

project:
    version: V1.0

swagger:
    enabled: true
    title: Object Detection System Backend Interface APIs
    description: Swagger implementation for the object detection system backend services, leveraging annotations at the controller-method level.
    useDefaultResponseMessages: false
    enableUrlTemplating: false
    deepLinking: true
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    displayOperationId: false
    displayRequestDuration: false
    filter: false
    maxDisplayedTags: 0
    showExtensions: false