server:
    port: 8080

spring:
    application:
        name: ods-demo

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/ods?autoReconnect=true&useSSL=false&useUnicode=true&amp;charaterEncoding=utf-8
        username: wumrwds

mybatis:
    config-location: classpath:mybatis.cfg.xml
    mapper-locations: classpath:mappers/*.xml

project:
    version: V1.0
